# Generated by Django 5.1.3 on 2024-11-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(max_length=1000),
        ),
    ]
